export type RoleEntry = {
  role: string;
  description: string;
  additional_details?: string;
};

export type RoleCategory = {
  id: string;
  label: string;
  icon: string;
  roles: RoleEntry[];
};

export const CEREMONY_ROLE_CATEGORIES: RoleCategory[] = [
  {
    id: 'entertainment',
    label: 'Entertainment & Performance',
    icon: 'Music',
    roles: [
      { role: 'Performer',               description: 'General live performer providing entertainment during the event.' },
      { role: 'Artist',                  description: 'Generic term for a creative performer appearing at the ceremony.' },
      { role: 'Musical Artist',          description: 'Solo singer or band delivering live musical performance.' },
      { role: 'Vocalist',                description: 'Live singer performing solo vocal acts during the ceremony.' },
      { role: 'Music Band',              description: 'Live band performing throughout the event or at specific segments.' },
      { role: 'Orchestra',               description: 'Classical music ensemble providing orchestral entertainment.' },
      { role: 'DJ',                      description: 'Provides music throughout the event including pre-show, intervals and post-ceremony.' },
      { role: 'Celebrity Performer',     description: 'Well-known public figure invited to perform for entertainment value.' },
      { role: 'Dance Performer',         description: 'Individual professional dancer performing choreographed routines.' },
      { role: 'Dance Group',             description: 'Professional dance troupe delivering group choreography.' },
      { role: 'Cultural Performer',      description: 'Artist delivering traditional or cultural performances relevant to the event theme.' },
      { role: 'Folk Artist',             description: 'Performer representing regional folk culture and traditional arts.' },
      { role: 'Classical Artist',        description: 'Performer specialising in classical music or classical dance forms.' },
      { role: 'Instrumentalist',         description: 'Musician who plays one or more musical instruments during the ceremony.' },
      { role: 'Stand-up Comedian',       description: 'Comedian providing entertainment between award segments to keep energy high.' },
      { role: 'Magician',                description: 'Performs close-up or stage magic illusion acts for guests.' },
      { role: 'Illusionist',             description: 'Stage illusion performer delivering large-scale visual spectacle.' },
      { role: 'Mime Artist',             description: 'Silent theatrical performer using gesture and movement without speech.' },
      { role: 'Poet',                    description: 'Delivers original or commissioned poetry recitals at the ceremony.' },
      { role: 'Spoken Word Artist',      description: 'Performs live spoken word — poetry, storytelling or performance prose.' },
      { role: 'Theatre Group',           description: 'Stage drama group delivering short theatrical performance.' },
      { role: 'Choir',                   description: 'Group vocal ensemble providing choral performance.' },
      { role: 'Children\'s Performer',   description: 'Provides youth-oriented entertainment where family attendance is expected.' },
      { role: 'Opening Act Performer',   description: 'Performer who opens the event and sets the tone for the evening.' },
      { role: 'Closing Performance Artist', description: 'Brings the entertainment programme to a memorable close.' },
      { role: 'Celebrity Guest Performer', description: 'Special celebrity guest delivering a surprise or headline performance.' },
      { role: 'Fashion Model',           description: 'Participates in fashion showcases or runway segments if applicable.', additional_details: 'Coordinate with fashion choreographer for runway sequence and styling.' },
      { role: 'Fashion Choreographer',   description: 'Directs and choreographs any fashion showcase sequences at the event.' },
      { role: 'Live Painter',            description: 'Creates an original artwork live on stage during the ceremony, often auctioned.' },
      { role: 'Digital Artist',          description: 'Delivers interactive digital art presentations or live digital creation.' },
      { role: 'LED Performance Group',   description: 'Technology-enhanced performance using LED suits, props or interactive lighting.' },
      { role: 'Fire Performer',          description: 'Specialty fire performance act.', additional_details: '⚠ Subject to venue regulations and fire safety approvals. Written venue permission required.' },
      { role: 'Acrobatic Performer',     description: 'Performs acrobatic or aerial acts such as silks, hoop or pole.' },
      { role: 'Circus Performer',        description: 'Specialty circus entertainment including juggling, stilt-walking or clowning.' },
      { role: 'Beatbox Artist',          description: 'Vocal percussion performer providing rhythmic entertainment.' },
      { role: 'Rap Artist',              description: 'Live rap or hip-hop performance act.' },
      { role: 'Motivational Performer',  description: 'Delivers an inspirational or motivational performance or presentation.' },
    ],
  },
  {
    id: 'ceremony',
    label: 'Ceremony & Protocol',
    icon: 'Mic2',
    roles: [
      { role: 'Master of Ceremonies (MC)', description: 'Hosts and guides the entire ceremony from start to finish. The central on-stage authority.', additional_details: 'Responsible for introductions, transitions, managing pace and keeping the audience engaged.' },
      { role: 'Co-Host',                  description: 'Shares hosting duties with the MC, typically alternating award presentations.' },
      { role: 'Event Host',               description: 'Overall event presenter responsible for welcoming guests and guiding proceedings.' },
      { role: 'Stage Host',               description: 'Manages on-stage flow, introduces presenters and maintains stage discipline.' },
      { role: 'Award Presenter',          description: 'Presents specific award categories on stage alongside envelope or trophy.' },
      { role: 'Trophy Presenter',         description: 'Carries and presents physical trophies to winners on stage.' },
      { role: 'Certificate Presenter',    description: 'Presents framed certificates or plaques to recipients.' },
      { role: 'Citation Reader',          description: 'Reads out nominations, citation texts and winner announcements.' },
      { role: 'Vote of Thanks Speaker',   description: 'Delivers the formal vote of thanks at the close of the ceremony.' },
      { role: 'Welcome Speaker',          description: 'Opens the ceremony with a welcome address on behalf of the organiser.' },
      { role: 'Opening Ceremony Lead',    description: 'Leads the official opening segment including any formal proceedings.' },
      { role: 'Closing Ceremony Lead',    description: 'Leads the formal closing segment and signs off the evening.' },
      { role: 'Protocol Officer',         description: 'Ensures ceremonial protocol, order of precedence and formal procedures are correctly observed.' },
      { role: 'VIP Liaison',              description: 'Manages VIP guest relations, movement and special requirements throughout the event.' },
      { role: 'Green Room Coordinator',   description: 'Manages backstage green room logistics including presenter briefings and timing cues.' },
    ],
  },
  {
    id: 'production',
    label: 'Production & Stage Crew',
    icon: 'Clapperboard',
    roles: [
      { role: 'Stage Manager',           description: 'Overall responsibility for all stage operations on the day of the event.', additional_details: 'Single point of authority for stage. Coordinates all cues and manages show running order.' },
      { role: 'Assistant Stage Manager', description: 'Supports the stage manager with logistics, cues and backstage coordination.' },
      { role: 'Production Director',     description: 'Oversees the full production from pre-production through to event day.' },
      { role: 'Show Director',           description: 'Directs the live show, calling shots and managing on-screen/stage presentation.' },
      { role: 'Technical Director',      description: 'Manages all technical systems including AV, lighting, sound and broadcasting infrastructure.' },
      { role: 'Floor Manager',           description: 'Manages activity on the venue floor, communicating between production and on-floor staff.' },
      { role: 'Cue Manager',             description: 'Calls production cues for lighting, sound and video in sequence with the running order.' },
      { role: 'Audio Engineer',          description: 'Designs and operates the complete audio system for the event.' },
      { role: 'Sound Technician',        description: 'Operates sound equipment including mixing desk, microphones and playback.' },
      { role: 'Lighting Designer',       description: 'Designs the complete lighting scheme for the stage and venue.' },
      { role: 'Lighting Technician',     description: 'Operates lighting rigs and executes lighting cues during the show.' },
      { role: 'AV Operator',             description: 'Operates audio-visual equipment including screens, switching and playback.' },
      { role: 'LED Wall Operator',       description: 'Manages content and transitions on LED display walls or screens.' },
      { role: 'Projection Operator',     description: 'Manages projectors and coordinates projected content with running order.' },
      { role: 'Live Stream Producer',    description: 'Produces and manages the live-stream broadcast output for online audiences.' },
      { role: 'Broadcast Director',      description: 'Directs the broadcast output, coordinating camera shots and production values.' },
      { role: 'Camera Operator',         description: 'Operates cameras for live recording, broadcast or highlight reel capture.' },
      { role: 'Drone Operator',          description: 'Operates aerial drone to capture overhead footage.', additional_details: '⚠ Check venue indoor drone policy and obtain necessary permissions.' },
      { role: 'Video Switcher Operator', description: 'Switches between camera feeds and video sources in real-time during the broadcast.' },
      { role: 'Teleprompter Operator',   description: 'Manages teleprompter scripts for speakers and presenters on stage.' },
      { role: 'Graphics Operator',       description: 'Creates and operates on-screen lower thirds, winner reveals and branded graphics.' },
      { role: 'Stage Crew',              description: 'General stage crew responsible for set-up, breakdown and on-night stage changes.' },
      { role: 'Backstage Coordinator',   description: 'Manages backstage flow, briefing presenters and ensuring on-time stage entries.' },
      { role: 'Props Manager',           description: 'Sources, tracks and manages all physical props required for the ceremony.' },
      { role: 'Set Designer',            description: 'Designs the stage set and visual concept for the ceremony environment.' },
      { role: 'Stage Decorator',         description: 'Executes stage decoration, floral arrangements and table dressing.' },
    ],
  },
  {
    id: 'photography',
    label: 'Photography & Content',
    icon: 'Camera',
    roles: [
      { role: 'Official Photographer',         description: 'Primary photographer responsible for all official imagery of the event.' },
      { role: 'Event Photographer',            description: 'General event photography covering arrivals, networking and ceremony.' },
      { role: 'Portrait Photographer',         description: 'Provides formal portrait sessions for nominees and guests.' },
      { role: 'Red Carpet Photographer',       description: 'Dedicated photographer covering the red carpet arrivals segment.' },
      { role: 'Official Videographer',         description: 'Primary videographer producing the official event recording and highlights.' },
      { role: 'Documentary Filmmaker',         description: 'Creates a documentary-style film capturing the full event story.' },
      { role: 'Social Media Content Creator',  description: 'Creates real-time content for social media channels throughout the event.' },
      { role: 'Behind-the-Scenes Creator',     description: 'Captures authentic behind-the-scenes content for social and editorial use.' },
      { role: 'Live Blogger',                  description: 'Provides live written coverage of the event for the website or press.' },
      { role: 'Interview Host',                description: 'Conducts on-the-spot red carpet and post-award interviews with guests.' },
      { role: 'Podcast Host',                  description: 'Records podcast content, interviews and highlights at the event.' },
      { role: 'Press Photographer',            description: 'Photographer representing external media outlets and press organisations.' },
    ],
  },
  {
    id: 'hospitality',
    label: 'Hospitality & Guest Experience',
    icon: 'UtensilsCrossed',
    roles: [
      { role: 'VIP Host',                  description: 'Dedicated personal host assigned to VIP guests throughout the evening.' },
      { role: 'Guest Relations Executive', description: 'Manages the overall guest experience from arrival to departure.' },
      { role: 'Hospitality Manager',       description: 'Oversees all hospitality operations, service standards and guest satisfaction.' },
      { role: 'Registration Executive',    description: 'Manages guest check-in, badge distribution and registration process.' },
      { role: 'Front Desk Executive',      description: 'Manages the front-of-house desk as the first point of contact for guests.' },
      { role: 'Concierge',                 description: 'Provides personalised assistance and information to guests throughout the event.' },
      { role: 'Ushers',                    description: 'Guides guests to their seats, directs movement and assists with queries.' },
      { role: 'Seating Coordinator',       description: 'Manages the table plan, seating assignments and resolves seating queries.' },
      { role: 'Welcome Team',              description: 'Greets guests warmly on arrival and provides a positive first impression.' },
      { role: 'Guest Escort',              description: 'Accompanies and personally escorts specific guests within the venue.' },
      { role: 'Cloakroom Attendant',       description: 'Manages secure storage of guest coats, bags and belongings.' },
      { role: 'Catering Coordinator',      description: 'Coordinates food and beverage service in liaison with the catering supplier.' },
    ],
  },
  {
    id: 'security',
    label: 'Security & Safety',
    icon: 'Shield',
    roles: [
      { role: 'Chief Security Officer',     description: 'Senior security lead with overall responsibility for event security.' },
      { role: 'Security Supervisor',        description: 'Supervises the security team on the ground throughout the event.' },
      { role: 'Security Guard',             description: 'Provides general security, access control and perimeter management.' },
      { role: 'VIP Security',               description: 'Dedicated close protection for VIP guests and principal speakers.' },
      { role: 'Emergency Response Officer', description: 'Manages emergency response protocols and evacuation procedures.' },
      { role: 'Fire Safety Officer',        description: 'Ensures full fire safety compliance, evacuation routes and fire-related risk management.' },
      { role: 'Medical Officer',            description: 'Qualified medical professional providing on-site medical support.' },
      { role: 'First Aid Team',             description: 'Trained first-aiders available throughout the event to administer first aid.' },
      { role: 'Crowd Control Officer',      description: 'Manages safe crowd flow, queue management and capacity monitoring.' },
    ],
  },
  {
    id: 'recognition',
    label: 'Special Recognition',
    icon: 'Star',
    roles: [
      { role: 'Patron',                       description: 'High-profile individual who lends their name and support to the awards.' },
      { role: 'Chief Patron',                 description: 'Highest-level patron, typically a senior dignitary or influential leader.' },
      { role: 'Honorary Patron',              description: 'Honorary patronage role recognising significant contribution to the cause.' },
      { role: 'Lifetime Patron',              description: 'Patron whose support and association with the awards spans their lifetime.' },
      { role: 'Honorary Guest',               description: 'Distinguished invited guest honoured for their achievements or standing.' },
      { role: 'Distinguished Alumnus/Alumna', description: 'A notable past nominee, winner or participant recognised for their subsequent achievements.' },
      { role: 'Goodwill Ambassador',          description: 'Promotes the values, mission and reputation of the awards programme.' },
      { role: 'Brand Champion',               description: 'An individual who actively champions the awards brand in their network.' },
      { role: 'Community Champion',           description: 'Represents and advocates for community interests connected to the awards.' },
      { role: 'Event Champion',               description: 'A key supporter and active promoter of the specific event.' },
      { role: 'Industry Champion',            description: 'A leading advocate from within the industry the awards serve.' },
    ],
  },
  {
    id: 'applicants',
    label: 'Applicants & Award Participants',
    icon: 'Trophy',
    roles: [
      { role: 'Nominator',                    description: 'Person who submits a nomination for someone else.' },
      { role: 'Self-Nominator',               description: 'Person or organisation nominating themselves for an award.' },
      { role: 'Nominee',                      description: 'Person or organisation that has been nominated for consideration.' },
      { role: 'Applicant',                    description: 'Nominee who completes and submits the full application form.' },
      { role: 'Candidate',                    description: 'General term for an eligible participant in the awards process.' },
      { role: 'Eligible Candidate',           description: 'Candidate who has passed the eligibility criteria screening.' },
      { role: 'Ineligible Candidate',         description: 'Candidate who failed eligibility screening and cannot proceed.' },
      { role: 'Verified Applicant',           description: 'Application has been verified and confirmed by organisers.' },
      { role: 'Under Review Applicant',       description: 'Application is currently being reviewed internally by the awards team.' },
      { role: 'Approved Applicant',           description: 'Application has been accepted and progressed to the judging stage.' },
      { role: 'Rejected Applicant',           description: 'Application was reviewed and formally rejected from the process.' },
      { role: 'Withdrawn Applicant',          description: 'Applicant who voluntarily withdrew their application.' },
      { role: 'Disqualified Candidate',       description: 'Candidate removed from the process due to a rule violation.' },
      { role: 'Quarter Finalist',             description: 'Selected to progress through the first elimination round.' },
      { role: 'Semi Finalist',                description: 'Selected to progress to the semi-final stage of judging.' },
      { role: 'Finalist',                     description: 'Selected by judges for the final round of award consideration.' },
      { role: "People's Choice Finalist",     description: 'Finalist selected through public voting rather than judge scoring.' },
      { role: 'Highly Commended',             description: 'Exceptional performance recognised but not awarded first place.' },
      { role: 'Merit Award Recipient',        description: 'Recognised for excellence at a merit level by the judging panel.' },
      { role: 'Special Recognition Recipient',description: 'Recipient of a special jury recognition outside standard categories.' },
      { role: 'Honourable Mention',           description: 'Recognition of achievement without placing in the top award positions.' },
      { role: 'Bronze Winner',                description: 'Third-place award winner in a category where tiered winners are awarded.' },
      { role: 'Silver Winner',                description: 'Second-place award winner in a category where tiered winners are awarded.' },
      { role: 'Gold Winner',                  description: 'First-place award winner in a category where tiered winners are awarded.' },
      { role: 'Second Runner-up',             description: 'Third-place finisher in the final award category ranking.' },
      { role: 'Runner-up',                    description: 'Second-place finisher in the final award category ranking.' },
      { role: 'Category Winner',              description: 'Winner of a specific award category at the ceremony.' },
      { role: 'Grand Winner',                 description: 'Overall award winner across all categories at the event.' },
      { role: 'Lifetime Achievement Recipient', description: 'Special recognition for outstanding contribution over an entire career.' },
      { role: 'Hall of Fame Inductee',        description: 'Permanently inducted into the awards Hall of Fame for sustained excellence.' },
      { role: 'Legacy Award Recipient',       description: 'Recognised specifically for long-term impact and lasting contribution.' },
      { role: 'Emerging Leader',              description: 'Rising talent awardee recognised for early-career achievement and potential.' },
      { role: 'Young Achiever',               description: 'Youth recognition award for outstanding achievement by a younger participant.' },
      { role: 'Outstanding Contributor',      description: 'Recognised for a significant individual contribution to the sector or event.' },
      { role: "People's Choice Winner",       description: 'Overall winner selected entirely by public vote.' },
    ],
  },
  {
    id: 'judging',
    label: 'Judging Roles',
    icon: 'Scale',
    roles: [
      { role: 'Judge',                    description: 'Reviews and scores applications according to the awards criteria.' },
      { role: 'Chief Judge',              description: 'Leads the judging panel and holds final authority over judging decisions.' },
      { role: 'Head Judge',               description: 'Oversees the judging process and ensures consistency across the panel.' },
      { role: 'Jury Member',              description: 'Individual member of the judging jury contributing scores and deliberation.' },
      { role: 'Jury Chair',               description: 'Chairs jury discussions, manages deliberations and facilitates consensus.' },
      { role: 'Independent Judge',        description: 'External, unbiased evaluator with no conflict of interest with applicants.' },
      { role: 'Technical Judge',          description: 'Specialist judge evaluating entries against technical criteria.' },
      { role: 'Industry Expert',          description: 'Sector specialist invited to judge categories within their area of expertise.' },
      { role: 'Guest Judge',              description: 'Invited for a specific category or session of judging.' },
      { role: 'Honorary Judge',           description: 'Prestigious judging role with honorary status — may not score directly.' },
      { role: 'Observer Judge',           description: 'Non-scoring observer present during judging to maintain transparency.' },
      { role: 'Audit Judge',              description: 'Reviews the judging process to confirm fairness and procedural compliance.' },
      { role: 'Verification Committee',   description: 'Panel that confirms applicant eligibility before judging commences.' },
      { role: 'Scoring Committee',        description: 'Reviews and reconciles final scores across the judging panel.' },
      { role: 'Appeals Committee',        description: 'Independently handles and resolves any formal disputes or appeals.' },
    ],
  },
  {
    id: 'organising',
    label: 'Organising Team',
    icon: 'Users',
    roles: [
      { role: 'Event Owner',              description: 'Ultimate owner and decision-maker for the awards programme.' },
      { role: 'Awards Director',          description: 'Leads strategic direction and overall delivery of the awards.' },
      { role: 'Event Director',           description: 'Directs overall event planning, logistics and execution.' },
      { role: 'Programme Director',       description: 'Manages the awards programme, timeline and participant journey.' },
      { role: 'Awards Manager',           description: 'Manages day-to-day operations including nominations, judging and communications.' },
      { role: 'Event Manager',            description: 'Coordinates all elements of the event from planning through to delivery.' },
      { role: 'Project Manager',          description: 'Manages project timelines, resources and deliverables across all workstreams.' },
      { role: 'Operations Manager',       description: 'Oversees on-the-ground operational logistics and event-day execution.' },
      { role: 'Awards Coordinator',       description: 'Coordinates the administrative and logistical elements of the awards.' },
      { role: 'Registration Manager',     description: 'Manages all aspects of participant and attendee registration.' },
      { role: 'Nomination Manager',       description: 'Oversees the nomination process, entry submissions and applicant communications.' },
      { role: 'Judging Coordinator',      description: 'Coordinates the judging process including panel scheduling and score collation.' },
      { role: 'Category Manager',         description: 'Manages a specific award category from nominations through to winner announcement.' },
      { role: 'Marketing Manager',        description: 'Leads marketing strategy and campaign execution for the awards.' },
      { role: 'Communications Manager',   description: 'Manages all internal and external communications for the programme.' },
      { role: 'PR Manager',               description: 'Manages public relations, media outreach and press coverage.' },
      { role: 'Sponsorship Manager',      description: 'Manages sponsor relationships, packages and fulfilment of sponsor benefits.' },
      { role: 'Partnership Manager',      description: 'Develops and manages strategic partner relationships.' },
      { role: 'Finance Manager',          description: 'Manages budgets, invoicing, payments and financial reporting.' },
      { role: 'Compliance Officer',       description: 'Ensures all awards processes comply with relevant regulations and policies.' },
      { role: 'Legal Advisor',            description: 'Provides legal counsel on terms, contracts, data and intellectual property.' },
      { role: 'Volunteer Coordinator',    description: 'Recruits, trains and manages the volunteer team for the event.' },
      { role: 'Logistics Manager',        description: 'Manages all logistical elements including venue, transport and equipment.' },
      { role: 'Venue Manager',            description: 'Liaises with the venue team and manages the venue relationship.' },
      { role: 'Production Manager',       description: 'Manages production suppliers, technical requirements and on-night production.' },
      { role: 'Technical Manager',        description: 'Oversees all technical systems and AV requirements for the event.' },
      { role: 'Hospitality Manager',      description: 'Manages hospitality, catering and guest experience delivery.' },
      { role: 'Security Manager',         description: 'Plans and manages all security arrangements for the event.' },
    ],
  },
  {
    id: 'sponsors',
    label: 'Sponsors',
    icon: 'Handshake',
    roles: [
      { role: 'Title Sponsor',            description: 'Headline sponsor whose name is part of the official awards title.' },
      { role: 'Presenting Sponsor',       description: 'Primary presenting partner whose branding leads all event communications.' },
      { role: 'Platinum Sponsor',         description: 'Highest tier commercial sponsor with premium branding and benefits.' },
      { role: 'Gold Sponsor',             description: 'Second-tier commercial sponsor with prominent branding benefits.' },
      { role: 'Silver Sponsor',           description: 'Third-tier commercial sponsor with standard branding benefits.' },
      { role: 'Bronze Sponsor',           description: 'Entry-level commercial sponsor with foundational benefits package.' },
      { role: 'Category Sponsor',         description: 'Sponsor associated exclusively with a specific award category.' },
      { role: 'Trophy Sponsor',           description: 'Sponsor who funds and brands the physical awards trophies.' },
      { role: 'Dinner Sponsor',           description: 'Sponsor of the awards dinner or post-ceremony gala meal.' },
      { role: 'Networking Sponsor',       description: 'Sponsor of the networking drinks or pre-event reception.' },
      { role: 'Media Sponsor',            description: 'Sponsor providing media coverage, advertising space or broadcast support.' },
      { role: 'Hospitality Sponsor',      description: 'Sponsor of VIP hospitality, lounge or exclusive guest experience.' },
      { role: 'Gift Sponsor',             description: 'Sponsor providing branded gifts, goody bags or delegate packs.' },
      { role: 'Technology Sponsor',       description: 'Sponsor providing technology, software or digital infrastructure.' },
      { role: 'Venue Sponsor',            description: 'Sponsor who funds or provides the event venue.' },
      { role: 'Travel Sponsor',           description: 'Sponsor covering travel arrangements for key participants or winners.' },
      { role: 'Sustainability Sponsor',   description: 'Sponsor supporting the environmental sustainability commitments of the event.' },
      { role: 'Charity Sponsor',          description: 'Sponsor whose contribution supports a designated charity partner.' },
    ],
  },
  {
    id: 'partners',
    label: 'Partners',
    icon: 'Network',
    roles: [
      { role: 'Strategic Partner',        description: 'Long-term strategic ally aligned with the awards mission and objectives.' },
      { role: 'Community Partner',        description: 'Partner representing and engaging a specific community or audience.' },
      { role: 'Industry Partner',         description: 'Partner from within the target industry sector the awards serve.' },
      { role: 'Knowledge Partner',        description: 'Partner providing intellectual capital, research or thought leadership.' },
      { role: 'Research Partner',         description: 'Partner contributing research, data insights or analytics to the programme.' },
      { role: 'Education Partner',        description: 'Academic institution or educational body partnering with the awards.' },
      { role: 'Government Partner',       description: 'Government body or public sector organisation partnering the event.' },
      { role: 'Chamber Partner',          description: 'Chamber of Commerce or trade body partnering with the programme.' },
      { role: 'Association Partner',      description: 'Professional association or industry body formally partnering the awards.' },
      { role: 'NGO Partner',              description: 'Non-governmental organisation aligned with the awards values and mission.' },
      { role: 'Corporate Partner',        description: 'Corporate entity contributing to the awards through a formal partnership.' },
      { role: 'Startup Partner',          description: 'Startup or emerging business partnering to gain visibility and association.' },
      { role: 'Innovation Partner',       description: 'Partner contributing innovation, new thinking or pioneering solutions.' },
      { role: 'Venue Partner',            description: 'Venue or hospitality business formally partnering with the event.' },
      { role: 'Ticketing Partner',        description: 'Partner managing ticket sales, distribution and registration services.' },
      { role: 'Technology Partner',       description: 'Technology provider delivering platforms, tools or technical infrastructure.' },
      { role: 'Event Partner',            description: 'General event partnership supporting delivery or promotion of the awards.' },
    ],
  },
  {
    id: 'brand_promotion',
    label: 'Brand Promotion',
    icon: 'Megaphone',
    roles: [
      { role: 'Brand Ambassador',         description: 'Officially represents and promotes the awards brand across their network.' },
      { role: 'Brand Ambassadress',       description: 'Female-identified official representative promoting the awards brand.' },
      { role: 'Event Ambassador',         description: 'Promotes the specific event to their audience and wider community.' },
      { role: 'Community Ambassador',     description: 'Represents the awards within a specific community or geographic area.' },
      { role: 'Student Ambassador',       description: 'Promotes the awards to student or early-career communities.' },
      { role: 'Digital Ambassador',       description: 'Promotes the awards through digital channels and online engagement.' },
      { role: 'Influencer',               description: 'Content creator with an established audience who promotes the awards organically or through partnership.' },
      { role: 'Social Media Influencer',  description: 'Influencer who promotes the awards specifically via social media platforms.' },
      { role: 'Key Opinion Leader',       description: 'Respected industry figure whose endorsement lends credibility to the awards.' },
      { role: 'Celebrity Endorser',       description: 'Well-known public figure who formally endorses and promotes the awards.' },
      { role: 'Campaign Advocate',        description: 'Active advocate for an awards campaign or nominations drive.' },
      { role: 'Promotional Partner',      description: 'Partner contributing promotional reach, audiences or media channels.' },
    ],
  },
  {
    id: 'exhibitors',
    label: 'Exhibitors',
    icon: 'Store',
    roles: [
      { role: 'Exhibitor',                description: 'Organisation with a stand or presence showcasing products or services.' },
      { role: 'Premium Exhibitor',        description: 'Exhibitor with a premium stand allocation and enhanced visibility.' },
      { role: 'Startup Exhibitor',        description: 'Early-stage startup company exhibiting at the awards event.' },
      { role: 'Innovation Showcase',      description: 'Exhibitor specifically showcasing a new product, concept or innovation.' },
      { role: 'Product Demonstrator',     description: 'Exhibitor conducting live product demonstrations for attendees.' },
      { role: 'Technology Showcase',      description: 'Exhibitor showcasing technology products, platforms or solutions.' },
      { role: 'Sponsor Exhibitor',        description: 'Sponsor who also has a physical exhibition presence at the event.' },
      { role: 'Recruitment Exhibitor',    description: 'Organisation exhibiting specifically to recruit talent or candidates.' },
      { role: 'Charity Exhibitor',        description: 'Charity or non-profit organisation with an exhibition presence.' },
    ],
  },
  {
    id: 'media',
    label: 'Advertising & Media',
    icon: 'Newspaper',
    roles: [
      { role: 'Advertiser',               description: 'Organisation that has booked advertising space within the awards programme or publication.' },
      { role: 'Media Partner',            description: 'Media organisation formally partnering to provide coverage of the event.' },
      { role: 'Print Media',              description: 'Print publication providing editorial or advertising coverage of the awards.' },
      { role: 'Digital Media',            description: 'Online media outlet providing digital coverage, articles or sponsored content.' },
      { role: 'Television Partner',       description: 'TV broadcaster covering, filming or broadcasting the awards.' },
      { role: 'Radio Partner',            description: 'Radio station covering the awards or hosting related content.' },
      { role: 'Press Representative',     description: 'Official press representative of a media outlet attending the event.' },
      { role: 'Journalist',               description: 'Reporter or writer covering the awards for editorial purposes.' },
      { role: 'Photographer',             description: 'Media photographer capturing imagery for editorial publication.' },
      { role: 'Videographer',             description: 'Media videographer producing footage for editorial or broadcast use.' },
      { role: 'Content Creator',          description: 'Digital content creator producing awards-related content for media channels.' },
      { role: 'Blogger',                  description: 'Independent blogger covering the awards for their own platform or audience.' },
      { role: 'Podcaster',                description: 'Podcast host covering the awards or interviewing participants for their show.' },
      { role: 'News Reporter',            description: 'Reporter providing live or post-event news coverage of the awards.' },
      { role: 'Media Correspondent',      description: 'Senior media representative providing in-depth correspondent coverage.' },
      { role: 'Social Media Reporter',    description: 'Journalist or creator covering the event live via social media channels.' },
    ],
  },
  {
    id: 'speakers_vip',
    label: 'Speakers & VIP Guests',
    icon: 'Mic',
    roles: [
      { role: 'Keynote Speaker',          description: 'Delivers the main keynote address at the awards event.' },
      { role: 'Guest Speaker',            description: 'Invited speaker delivering a presentation or address at the event.' },
      { role: 'VIP Speaker',              description: 'High-profile invited speaker with VIP status at the ceremony.' },
      { role: 'Opening Speaker',          description: 'Delivers the opening address at the start of the awards ceremony.' },
      { role: 'Closing Speaker',          description: 'Delivers the closing address at the conclusion of the ceremony.' },
      { role: 'Presenter',                description: 'Delivers a specific presentation or talk during the event programme.' },
      { role: 'Panel Moderator',          description: 'Facilitates and moderates a panel discussion or debate session.' },
      { role: 'Panellist',                description: 'Participant in a panel discussion contributing expertise and perspective.' },
      { role: 'Celebrity Guest',          description: 'Well-known public figure invited as a special guest of the event.' },
      { role: 'Chief Guest',              description: 'Principal guest of honour holding the most senior guest status.' },
      { role: 'Guest of Honour',          description: 'Distinguished guest formally recognised and honoured at the ceremony.' },
      { role: 'Dignitary',                description: 'Senior public figure or official attending in a formal capacity.' },
      { role: 'VIP Guest',                description: 'Very important person guest with priority access and dedicated hospitality.' },
      { role: 'Distinguished Guest',      description: 'Specially invited guest of notable standing or achievement.' },
      { role: 'Government Official',      description: 'Representative from a government department or statutory body.' },
      { role: 'Minister',                 description: 'Government minister attending in an official or invited capacity.' },
      { role: 'Mayor',                    description: 'Elected mayor of a city or borough attending the awards.' },
      { role: 'Member of Parliament',     description: 'Elected Member of Parliament attending in an official capacity.' },
      { role: 'CEO Guest',                description: 'Chief Executive of a partner, sponsor or industry organisation attending.' },
      { role: 'Board Member',             description: 'Board-level executive attending in a leadership or governance capacity.' },
      { role: 'Special Invitee',          description: 'Individual with a specific personal invitation from the organiser.' },
    ],
  },
  {
    id: 'attendees',
    label: 'Attendees & Delegates',
    icon: 'Ticket',
    roles: [
      { role: 'Attendee',                 description: 'General registered attendee at the awards event.' },
      { role: 'Delegate',                 description: 'Official delegate attending on behalf of an organisation.' },
      { role: 'Visitor',                  description: 'Day visitor or casual attendee at the event.' },
      { role: 'Guest',                    description: 'Invited guest attending the event at the invitation of another party.' },
      { role: 'Corporate Guest',          description: 'Guest attending as a representative of a corporate organisation.' },
      { role: 'Table Host',               description: 'Individual responsible for hosting a table of guests at the awards dinner.' },
      { role: 'Table Guest',              description: 'Guest seated at a hosted table as part of a corporate or group booking.' },
      { role: 'Ticket Holder',            description: 'Person who has purchased a ticket and is registered to attend.' },
      { role: 'VIP Ticket Holder',        description: 'Holder of a VIP ticket with access to premium areas and experiences.' },
      { role: 'Student Attendee',         description: 'Student attending as part of an educational or development opportunity.' },
      { role: 'Alumni Guest',             description: 'Past participant, winner or attendee returning as a guest.' },
      { role: 'Family Guest',             description: 'Family member of a nominee or winner attending to support them.' },
    ],
  },
  {
    id: 'voting',
    label: 'Voting Roles',
    icon: 'CheckSquare',
    roles: [
      { role: 'Public Voter',             description: 'Member of the general public participating in open public voting.' },
      { role: 'Registered Voter',         description: 'Individual who has formally registered to participate in the voting process.' },
      { role: 'Verified Voter',           description: 'Voter whose identity and eligibility to vote has been verified.' },
      { role: 'Jury Voter',               description: 'Member of the judging jury casting a formal vote on finalists.' },
      { role: 'Community Voter',          description: 'Voter representing and voting on behalf of a specific community.' },
      { role: 'Fan Voter',                description: 'Supporter or fan voting for their preferred nominee or candidate.' },
    ],
  },
  {
    id: 'volunteers',
    label: 'Volunteers',
    icon: 'Heart',
    roles: [
      { role: 'Volunteer',                description: 'General volunteer supporting event delivery across various functions.' },
      { role: 'Registration Volunteer',   description: 'Volunteer assisting at the registration and check-in desk.' },
      { role: 'Stage Volunteer',          description: 'Volunteer supporting on-stage and backstage operations.' },
      { role: 'Hospitality Volunteer',    description: 'Volunteer assisting with guest hospitality and experience.' },
      { role: 'Technical Volunteer',      description: 'Volunteer providing technical support and assistance.' },
      { role: 'Runner',                   description: 'Volunteer responsible for running messages, items or cues across the venue.' },
      { role: 'Event Marshal',            description: 'Volunteer managing crowd flow, access control and general marshal duties.' },
      { role: 'Information Desk Volunteer', description: 'Volunteer staffing the information point and answering guest queries.' },
    ],
  },
  {
    id: 'vendors',
    label: 'Vendors & Service Providers',
    icon: 'Package',
    roles: [
      { role: 'Caterer',                  description: 'Food and beverage provider responsible for the event catering.' },
      { role: 'Decorator',                description: 'Provides event décor, styling, centrepieces and venue dressing.' },
      { role: 'Audio Vendor',             description: 'Supplier providing sound equipment, PA systems and audio technology.' },
      { role: 'Lighting Vendor',          description: 'Supplier providing lighting rigs, fixtures and lighting technology.' },
      { role: 'AV Team',                  description: 'Audio-visual team providing full AV production services.' },
      { role: 'Security Agency',          description: 'Professional security agency supplying trained security personnel.' },
      { role: 'Printing Vendor',          description: 'Supplier responsible for event print collateral including programmes and signage.' },
      { role: 'Trophy Supplier',          description: 'Manufacturer or supplier producing the physical awards trophies.' },
      { role: 'Certificate Printer',      description: 'Supplier producing and printing winner certificates and plaques.' },
      { role: 'Florist',                  description: 'Provides floral arrangements for stage, tables and venue decoration.' },
      { role: 'Entertainment Provider',   description: 'Agency or individual providing entertainment acts and performers.' },
      { role: 'Live Band',                description: 'Live music band contracted to perform at the event.' },
      { role: 'Transport Provider',       description: 'Transport company providing vehicle logistics, shuttles or VIP transfers.' },
    ],
  },
  {
    id: 'technology',
    label: 'Technology Roles',
    icon: 'Monitor',
    roles: [
      { role: 'Platform Administrator',   description: 'Manages and maintains the awards management platform.' },
      { role: 'Event Administrator',      description: 'Administers a specific event within the platform.' },
      { role: 'Super Administrator',      description: 'Full administrative control across all events and platform settings.' },
      { role: 'CRM Administrator',        description: 'Manages the CRM system and data relationships for the awards.' },
      { role: 'Website Administrator',    description: 'Manages the awards website content, pages and technical settings.' },
      { role: 'Database Administrator',   description: 'Manages the backend database, data integrity and system performance.' },
      { role: 'System Auditor',           description: 'Reviews system access, activity logs and compliance with IT policies.' },
      { role: 'Technical Support',        description: 'Provides technical assistance to users experiencing platform issues.' },
      { role: 'Helpdesk Executive',       description: 'Front-line support agent assisting users with queries and problems.' },
      { role: 'Live Stream Operator',     description: 'Manages the technical delivery of the live stream broadcast.' },
      { role: 'Broadcast Engineer',       description: 'Senior engineer responsible for broadcast signal, encoding and distribution.' },
    ],
  },
  {
    id: 'governance',
    label: 'Governance & Compliance',
    icon: 'FileCheck',
    roles: [
      { role: 'Advisory Board Member',    description: 'Member of the awards advisory board providing strategic guidance.' },
      { role: 'Steering Committee Member',description: 'Member of the steering committee overseeing awards direction and governance.' },
      { role: 'Ethics Committee',         description: 'Committee responsible for ethical oversight and integrity of the awards.' },
      { role: 'Independent Auditor',      description: 'External independent auditor reviewing process fairness and compliance.' },
      { role: 'Data Protection Officer',  description: 'Responsible for GDPR compliance and data protection obligations.' },
      { role: 'Risk Manager',             description: 'Identifies, assesses and manages risks across the awards programme.' },
      { role: 'Legal Counsel',            description: 'Provides legal advice on contracts, IP, terms and regulatory compliance.' },
    ],
  },
  {
    id: 'post_event',
    label: 'Post-Event & Alumni',
    icon: 'Archive',
    roles: [
      { role: 'Alumni Winner',            description: 'Past award winner who remains connected to the awards community.' },
      { role: 'Past Winner',              description: 'Previous winner of an award category in an earlier year.' },
      { role: 'Past Judge',               description: 'Individuals who have previously served on the judging panel.' },
      { role: 'Past Sponsor',             description: 'Organisation that has previously sponsored the awards.' },
      { role: 'Legacy Member',            description: 'Long-standing member of the awards community with multi-year involvement.' },
      { role: 'Hall of Fame Member',      description: 'Permanently recognised member of the awards Hall of Fame.' },
      { role: 'Award Champion',           description: 'Past participant who actively champions the awards to new audiences.' },
      { role: 'Event Advocate',           description: 'Former attendee or participant who advocates for the awards programme.' },
      { role: 'Mentor',                   description: 'Experienced past participant offering mentoring to new applicants.' },
      { role: 'Community Leader',         description: 'Influential figure within the awards alumni and ongoing community.' },
    ],
  },
  {
    id: 'platform_roles',
    label: 'Platform & Account Roles',
    icon: 'UserCog',
    roles: [
      { role: 'Super Admin',              description: 'Full platform control across all events and organisational settings.', additional_details: 'Highest permission level — assign with care.' },
      { role: 'Organisation Admin',       description: 'Manages a specific organisation and all its associated events.' },
      { role: 'Event Admin',              description: 'Creates and manages a specific event within the platform.' },
      { role: 'Awards Manager',           description: 'Oversees categories, nominations and the judging workflow.' },
      { role: 'Category Manager',         description: 'Manages award categories and their associated questions and criteria.' },
      { role: 'Reviewer',                 description: 'Performs initial compliance and eligibility checks on submitted applications.' },
      { role: 'Public Voter',             description: 'Platform account for participating in public voting rounds.' },
      { role: 'Sponsor Representative',   description: 'Manages sponsorship benefits, branding assets and sponsor portal access.' },
      { role: 'Partner Representative',   description: 'Manages partnership deliverables and partner portal access.' },
      { role: 'Ambassador',               description: 'Promotes the event and tracks referrals via the platform.' },
      { role: 'Advertiser',               description: 'Books and manages advertising placements within the awards platform.' },
      { role: 'Speaker',                  description: 'Manages speaking session details, biography and speaker resources.' },
      { role: 'Media',                    description: 'Accesses press resources, media kits and event coverage materials.' },
      { role: 'Finance/Admin',            description: 'Handles payments, invoices, refunds and financial reporting.' },
      { role: 'Support Agent',            description: 'Assists users with platform queries and provides helpdesk support.' },
    ],
  },
];

export const ALL_ROLES_FLAT = CEREMONY_ROLE_CATEGORIES.flatMap(cat =>
  cat.roles.map(r => ({ ...r, category: cat.label, category_id: cat.id })),
);
