export type FieldType = 'text' | 'textarea' | 'email' | 'tel' | 'url' | 'number' | 'date' | 'datetime-local' | 'time' | 'select' | 'image';

export type FieldConfig = {
  key: string;
  label: string;
  type: FieldType;
  options?: string[];
  optionsByParent?: Record<string, string[]>;
  dependsOn?: string;
  required?: boolean;
  placeholder?: string;
  fullWidth?: boolean;
  masterDataUrl?: string; // fetch options dynamically from this API endpoint
};

export type EventTabConfig = {
  id: string;
  label: string;
  icon: string;
  type: string;
  description: string;
  fields: FieldConfig[];
  displayField: string;
  subField?: string;
  statusField?: string;
  tableColumns?: { key: string; label: string }[]; // if set, renders a table view instead of cards
};

export const EVENT_TABS: EventTabConfig[] = [
  {
    id: 'industry',
    label: 'Event Industry',
    icon: 'Factory',
    type: 'industry',
    description: 'Add industry sectors and classifications for this event.',
    displayField: 'name',
    subField: 'sub_sector',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Technology', fullWidth: true },
      { key: 'code', label: 'Code', type: 'text', placeholder: 'e.g. TECH-01', fullWidth: true },
      { key: 'description', label: 'Description', type: 'text', placeholder: 'Brief description of this industry', fullWidth: true },
    ],
  },
  {
    id: 'leadership',
    label: 'Leadership Boards',
    icon: 'Crown',
    type: 'leadership_board',
    description: 'Manage advisory board members, patrons, and leadership figures for this event.',
    displayField: 'title',
    subField: 'business',
    statusField: 'type',
    fields: [
      { key: 'first_name', label: 'First Name', type: 'text', placeholder: 'First name' },
      { key: 'last_name', label: 'Last Name', type: 'text', placeholder: 'Last name' },
      { key: 'title', label: 'Title', type: 'text', required: true, placeholder: 'e.g. Advisory Board Chair' },
      { key: 'description', label: 'Description', type: 'textarea', required: true, fullWidth: true, placeholder: 'Brief description' },
      { key: 'business', label: 'Business', type: 'text', placeholder: 'Company / Organisation' },
      { key: 'position', label: 'Position', type: 'text', placeholder: 'e.g. CEO, Director' },
      { key: 'type', label: 'Type', type: 'select', masterDataUrl: '/api/organiser/leadership-types' },
      { key: 'image_url', label: 'Image', type: 'image', fullWidth: true },
      { key: 'issue_date', label: 'Issue Date', type: 'datetime-local' },
      { key: 'expire_date', label: 'Expire Date', type: 'datetime-local' },
    ],
  },
  {
    id: 'agenda',
    label: 'Agenda',
    icon: 'Clock',
    type: 'agenda',
    description: 'Build the full event schedule with sessions, breaks, and keynotes.',
    displayField: 'title',
    subField: 'start_time',
    statusField: 'video_type',
    tableColumns: [
      { key: 'title',       label: 'Title' },
      { key: 'description', label: 'Description' },
      { key: 'hall_type',   label: 'Hall Type' },
      { key: 'type',        label: 'Agenda Type' },
      { key: 'status',      label: 'Status' },
    ],
    fields: [
      { key: 'title',       label: 'Title',            type: 'text',     required: true, placeholder: 'e.g. Opening Keynote', fullWidth: true },
      { key: 'description', label: 'Description',      type: 'textarea', fullWidth: true },
      { key: 'time',        label: 'Session Time',     type: 'select',   options: ['15 Mins','30 Mins','45 Mins','1 Hour','1.5 Hours','2 Hours','2.5 Hours','3 Hours','Half Day','Full Day'] },
      { key: 'buffer_time', label: 'Buffer Time',      type: 'select',   options: ['5 Mins','10 Mins','15 Mins','20 Mins','30 Mins','45 Mins','60 Mins'] },
      { key: 'hall_type',   label: 'Agenda Hall Type', type: 'select',   options: ['Main Hall','Conference Room','Exhibition Hall','Breakout Room','Seminar / Webinar','Networking Lounge','VIP Room','Outdoor Venue'] },
      { key: 'type',        label: 'Agenda Type',      type: 'select',   options: ['PDF','Video','Audio','Live Stream','Presentation','Workshop','Panel','Keynote','Networking','Exhibition','Awards','Entertainment','Other'] },
      { key: 'layout',      label: 'Layout',           type: 'select',   options: ['Standard','Timeline','Grid','Compact','Detailed'] },
      { key: 'status',      label: 'Status',           type: 'select',   options: ['Active','Inactive','Draft'] },
      { key: 'timezone',    label: 'Timezone',         type: 'select',   options: ['(UTC+00:00) GMT / London','(UTC+01:00) BST / London Summer','(UTC+05:30) Asia/Kolkata','(UTC-05:00) EST / New York','(UTC-08:00) PST / Los Angeles','(UTC+08:00) CST / Beijing','(UTC+09:00) JST / Tokyo','(UTC+10:00) AEST / Sydney'] },
      { key: 'attachment',  label: 'Attachment',       type: 'image',    fullWidth: false },
    ],
  },
  {
    id: 'team',
    label: 'My Team',
    icon: 'Users',
    type: 'team',
    description: 'Manage your internal event organising team members and their roles.',
    displayField: 'name',
    subField: 'role',
    statusField: 'status',
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'role', label: 'Role', type: 'text', required: true, placeholder: 'e.g. Event Coordinator' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'On Leave', 'Inactive'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'visitor',
    label: 'Manage Visitor',
    icon: 'UserCheck',
    type: 'visitor',
    description: 'Track visitor registrations and attendance.',
    displayField: 'name',
    subField: 'company',
    statusField: 'registration_status',
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'job_title', label: 'Job Title', type: 'text' },
      { key: 'ticket_type', label: 'Ticket Type', type: 'select', options: ['Standard', 'VIP', 'Student', 'Press', 'Complimentary'] },
      { key: 'registration_status', label: 'Status', type: 'select', options: ['Registered', 'Confirmed', 'Attended', 'No-show', 'Cancelled'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'exhibitor',
    label: 'Manage Exhibitor',
    icon: 'Store',
    type: 'exhibitor',
    description: 'Manage companies exhibiting at the event.',
    displayField: 'company',
    subField: 'package',
    statusField: 'status',
    fields: [
      { key: 'company', label: 'Company Name', type: 'text', required: true },
      { key: 'contact_name', label: 'Contact Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'booth_number', label: 'Booth / Stand Number', type: 'text' },
      { key: 'package', label: 'Package', type: 'select', options: ['Startup Booth', 'Standard Booth', 'Premium Booth', 'Corner Booth', 'Island Booth', 'Outdoor Booth'] },
      { key: 'industry', label: 'Industry', type: 'text' },
      { key: 'website', label: 'Website', type: 'url', fullWidth: true },
      { key: 'status', label: 'Status', type: 'select', options: ['Enquiry', 'Confirmed', 'Paid', 'Set Up', 'Completed', 'Cancelled'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'sponsorship',
    label: 'Manage Sponsorship',
    icon: 'Handshake',
    type: 'sponsorship',
    description: 'Manage event sponsors, tiers, and deal values.',
    displayField: 'company',
    subField: 'tier',
    statusField: 'status',
    fields: [
      { key: 'company', label: 'Company Name', type: 'text', required: true },
      { key: 'contact_name', label: 'Contact Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'tier', label: 'Sponsorship Tier', type: 'select', options: ['Title', 'Presenting', 'Platinum', 'Gold', 'Silver', 'Bronze', 'Category', 'Trophy', 'Dinner', 'Digital'] },
      { key: 'amount', label: 'Value (£)', type: 'number', placeholder: '0.00' },
      { key: 'status', label: 'Status', type: 'select', options: ['Prospecting', 'Proposal Sent', 'Negotiating', 'Confirmed', 'Contract Signed', 'Paid', 'Declined', 'Cancelled'] },
      { key: 'contract_date', label: 'Contract Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'speaker_slots',
    label: 'Speaker Slots',
    icon: 'CalendarDays',
    type: 'speaker_slot',
    description: 'Define available speaking slots and session formats.',
    displayField: 'title',
    subField: 'time',
    statusField: 'status',
    fields: [
      { key: 'time', label: 'Start Time', type: 'time', required: true },
      { key: 'end_time', label: 'End Time', type: 'time' },
      { key: 'title', label: 'Slot Title', type: 'text', required: true, placeholder: 'e.g. Keynote Address' },
      { key: 'format', label: 'Format', type: 'select', options: ['Keynote', 'Panel', 'Workshop', 'Fireside Chat', 'Lightning Talk', 'Q&A', 'Presentation'] },
      { key: 'room', label: 'Room / Stage', type: 'text' },
      { key: 'capacity', label: 'Capacity', type: 'number' },
      { key: 'speaker_name', label: 'Assigned Speaker', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Available', 'Reserved', 'Confirmed', 'Filled'] },
    ],
  },
  {
    id: 'speaker',
    label: 'Manage Speaker',
    icon: 'Mic',
    type: 'speaker',
    description: 'Manage speakers, their profiles, and session assignments.',
    displayField: 'name',
    subField: 'company',
    statusField: 'status',
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'job_title', label: 'Job Title', type: 'text' },
      { key: 'company', label: 'Company / Organisation', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'topic', label: 'Speaking Topic', type: 'text', fullWidth: true },
      { key: 'photo_url', label: 'Photo URL', type: 'url', fullWidth: true },
      { key: 'linkedin_url', label: 'LinkedIn URL', type: 'url', fullWidth: true },
      { key: 'bio', label: 'Biography', type: 'textarea', fullWidth: true },
      { key: 'fee', label: 'Speaker Fee (£)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Invited', 'Confirmed', 'Briefed', 'Declined', 'Completed'] },
    ],
  },
  {
    id: 'speaker_questionnaire',
    label: 'Speaker Questionnaire',
    icon: 'ClipboardList',
    type: 'speaker_questionnaire',
    description: 'Define questions to send to speakers for their profile and session information.',
    displayField: 'question',
    statusField: 'required',
    fields: [
      { key: 'question', label: 'Question', type: 'textarea', required: true, fullWidth: true, placeholder: 'e.g. Please provide a short biography (max 100 words)' },
      { key: 'question_type', label: 'Answer Type', type: 'select', options: ['Text', 'Long Text', 'Yes/No', 'Multiple Choice', 'File Upload'] },
      { key: 'required', label: 'Required', type: 'select', options: ['Yes', 'No'] },
      { key: 'display_order', label: 'Display Order', type: 'number', placeholder: '1' },
    ],
  },
  {
    id: 'banner_stand',
    label: 'Banner Stand',
    icon: 'Flag',
    type: 'banner_stand',
    description: 'Manage exhibition banner stands and their placement.',
    displayField: 'company',
    subField: 'type',
    statusField: 'status',
    fields: [
      { key: 'company', label: 'Company / Organisation', type: 'text', required: true },
      { key: 'contact_name', label: 'Contact Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'type', label: 'Stand Type', type: 'select', options: ['Pull-up Banner', 'Pop-up Stand', 'Exhibition Stand', 'Digital Display', 'Backdrop', 'Step & Repeat'] },
      { key: 'size', label: 'Size', type: 'select', options: ['Standard (85cm x 200cm)', 'Large (150cm x 200cm)', 'Extra Large (200cm x 200cm)', 'Custom'] },
      { key: 'location', label: 'Placement Location', type: 'text', placeholder: 'e.g. Entrance, Registration Desk' },
      { key: 'status', label: 'Status', type: 'select', options: ['Booked', 'Artwork Pending', 'Artwork Received', 'Printed', 'Installed', 'Completed'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'advertiser',
    label: 'Manage Advertiser',
    icon: 'Megaphone',
    type: 'advertiser',
    description: 'Manage advertisers and their placements across the event.',
    displayField: 'company',
    subField: 'ad_type',
    statusField: 'status',
    fields: [
      { key: 'company', label: 'Company Name', type: 'text', required: true },
      { key: 'contact_name', label: 'Contact Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'ad_type', label: 'Ad Type', type: 'select', options: ['Homepage Banner', 'Category Banner', 'Newsletter', 'LED Screen', 'Stage Backdrop', 'Program Guide', 'Social Media', 'Podcast'] },
      { key: 'placement', label: 'Placement Details', type: 'text', fullWidth: true },
      { key: 'amount', label: 'Value (£)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Booked', 'Artwork Pending', 'Live', 'Completed', 'Cancelled'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'magazine',
    label: 'Manage Magazine',
    icon: 'BookOpen',
    type: 'magazine',
    description: 'Manage event publication, magazine features, and editorial content.',
    displayField: 'title',
    subField: 'content_type',
    statusField: 'status',
    fields: [
      { key: 'title', label: 'Feature Title', type: 'text', required: true },
      { key: 'company', label: 'Company / Subject', type: 'text' },
      { key: 'contact_name', label: 'Contact Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'content_type', label: 'Content Type', type: 'select', options: ['Feature Article', 'Interview', 'Advertorial', 'Supplement', 'Winner Profile', 'Sponsor Showcase', 'Opinion Piece'] },
      { key: 'edition', label: 'Edition / Issue', type: 'text' },
      { key: 'issue_date', label: 'Publication Date', type: 'date' },
      { key: 'word_count', label: 'Word Count', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Briefed', 'Writing', 'In Review', 'Approved', 'Published'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'partner',
    label: 'Manage Partner',
    icon: 'Network',
    type: 'partner',
    description: 'Manage event partners and partnership agreements.',
    displayField: 'company',
    subField: 'type',
    statusField: 'status',
    fields: [
      { key: 'company', label: 'Company / Organisation', type: 'text', required: true },
      { key: 'contact_name', label: 'Contact Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'type', label: 'Partnership Type', type: 'select', options: ['Strategic', 'Industry', 'Media', 'Technology', 'Charity', 'Government', 'Education', 'Chamber', 'Community'] },
      { key: 'benefits', label: 'Benefits Offered', type: 'textarea', fullWidth: true },
      { key: 'status', label: 'Status', type: 'select', options: ['Prospecting', 'Proposal Sent', 'Confirmed', 'Active', 'Completed'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'marketer',
    label: 'Manage Marketer',
    icon: 'TrendingUp',
    type: 'marketer',
    description: 'Track marketing partners, campaigns, and promotional channels.',
    displayField: 'name',
    subField: 'channel',
    statusField: 'status',
    fields: [
      { key: 'name', label: 'Contact Name', type: 'text', required: true },
      { key: 'company', label: 'Company / Agency', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'channel', label: 'Marketing Channel', type: 'select', options: ['Email', 'Social Media', 'PR', 'Digital Ads', 'Print', 'Radio', 'Podcast', 'Influencer', 'SEO', 'Events'] },
      { key: 'campaign', label: 'Campaign / Activity', type: 'text', fullWidth: true },
      { key: 'budget', label: 'Budget (£)', type: 'number' },
      { key: 'reach', label: 'Estimated Reach', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Planning', 'Active', 'Paused', 'Completed'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'pub_contacts',
    label: 'Publication Contacts',
    icon: 'Newspaper',
    type: 'publication_contact',
    description: 'Manage press and media publication contacts.',
    displayField: 'name',
    subField: 'publication',
    statusField: 'status',
    fields: [
      { key: 'name', label: 'Contact Name', type: 'text', required: true },
      { key: 'publication', label: 'Publication / Media Outlet', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'type', label: 'Media Type', type: 'select', options: ['Print', 'Online', 'Broadcast TV', 'Broadcast Radio', 'Podcast', 'Blog', 'Newsletter'] },
      { key: 'circulation', label: 'Circulation / Audience', type: 'text' },
      { key: 'press_pass', label: 'Press Pass Issued', type: 'select', options: ['Yes', 'No', 'Pending'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Contacted', 'Confirmed', 'Declined', 'Published Coverage'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'download',
    label: 'Manage Download',
    icon: 'Download',
    type: 'download',
    description: 'Manage downloadable resources and documents for this event.',
    displayField: 'title',
    subField: 'file_type',
    statusField: 'access',
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, placeholder: 'e.g. Event Programme 2025' },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'file_url', label: 'File URL', type: 'url', fullWidth: true, required: true },
      { key: 'file_type', label: 'File Type', type: 'select', options: ['PDF', 'Word Document', 'Excel', 'PowerPoint', 'Image', 'Video', 'ZIP', 'Other'] },
      { key: 'access', label: 'Access Level', type: 'select', options: ['Public', 'Registered Only', 'VIP Only', 'Internal Only'] },
      { key: 'category', label: 'Category', type: 'select', options: ['Programme', 'Brochure', 'Sponsorship Pack', 'Media Kit', 'Presentation', 'Report', 'Guidelines', 'Other'] },
    ],
  },
  {
    id: 'artwork',
    label: 'Manage Artwork',
    icon: 'Palette',
    type: 'artwork',
    description: 'Manage event design assets, artwork, and branding files.',
    displayField: 'title',
    subField: 'type',
    statusField: 'status',
    fields: [
      { key: 'title', label: 'Artwork Title', type: 'text', required: true },
      { key: 'type', label: 'Artwork Type', type: 'select', options: ['Logo', 'Banner', 'Poster', 'Social Media Graphic', 'Certificate', 'Trophy Design', 'Backdrop', 'Stage Design', 'Email Header', 'Other'] },
      { key: 'file_url', label: 'File URL', type: 'url', fullWidth: true },
      { key: 'dimensions', label: 'Dimensions / Spec', type: 'text', placeholder: 'e.g. 1920x1080px' },
      { key: 'format', label: 'Format', type: 'select', options: ['JPG', 'PNG', 'SVG', 'PDF', 'AI', 'EPS', 'PSD', 'GIF', 'MP4'] },
      { key: 'designer', label: 'Designer / Agency', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'In Review', 'Approved', 'In Use', 'Archived'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'content',
    label: 'Content Writing',
    icon: 'PenTool',
    type: 'content',
    description: 'Manage written content, press releases, and copy for the event.',
    displayField: 'title',
    subField: 'type',
    statusField: 'status',
    fields: [
      { key: 'title', label: 'Content Title', type: 'text', required: true },
      { key: 'type', label: 'Content Type', type: 'select', options: ['Blog Post', 'Press Release', 'Social Media Post', 'Newsletter', 'Website Copy', 'Speech', 'Award Citation', 'Announcement', 'Email Copy'] },
      { key: 'author', label: 'Author / Writer', type: 'text' },
      { key: 'publish_date', label: 'Publish Date', type: 'date' },
      { key: 'word_count', label: 'Word Count', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Brief', 'Writing', 'In Review', 'Approved', 'Published', 'Archived'] },
      { key: 'content', label: 'Content', type: 'textarea', fullWidth: true, placeholder: 'Write or paste content here…' },
    ],
  },
  {
    id: 'promotions',
    label: 'Manage Promotions',
    icon: 'Tag',
    type: 'promotion',
    description: 'Manage discount codes, promotional offers, and campaigns.',
    displayField: 'name',
    subField: 'code',
    statusField: 'status',
    fields: [
      { key: 'name', label: 'Promotion Name', type: 'text', required: true, placeholder: 'e.g. Early Bird 20% Off' },
      { key: 'code', label: 'Promo Code', type: 'text', placeholder: 'e.g. EARLY2025' },
      { key: 'discount_type', label: 'Discount Type', type: 'select', options: ['Percentage (%)', 'Fixed Amount (£)', 'Free Ticket', 'Upgrade'] },
      { key: 'discount_value', label: 'Discount Value', type: 'number' },
      { key: 'valid_from', label: 'Valid From', type: 'date' },
      { key: 'valid_until', label: 'Valid Until', type: 'date' },
      { key: 'max_uses', label: 'Max Uses', type: 'number', placeholder: 'Leave blank for unlimited' },
      { key: 'target', label: 'Target Audience', type: 'select', options: ['All', 'Nominees', 'Sponsors', 'Exhibitors', 'Attendees', 'VIP', 'Partners'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Active', 'Paused', 'Expired'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'exhibitor_info',
    label: 'Exhibitor Information',
    icon: 'Info',
    type: 'exhibitor_info',
    description: 'Provide setup instructions, regulations, and logistics info for exhibitors.',
    displayField: 'title',
    subField: 'section',
    statusField: 'important',
    fields: [
      { key: 'section', label: 'Section', type: 'select', required: true, options: ['Setup Instructions', 'Rules & Regulations', 'Health & Safety', 'Logistics', 'Technical Requirements', 'Catering', 'Parking', 'FAQ', 'Other'] },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'important', label: 'Priority', type: 'select', options: ['High', 'Medium', 'Low'] },
      { key: 'content', label: 'Content', type: 'textarea', fullWidth: true, required: true, placeholder: 'Provide detailed information for exhibitors…' },
    ],
  },
  {
    id: 'photos',
    label: 'Manage Photos',
    icon: 'Camera',
    type: 'photo',
    description: 'Manage event photos, galleries, and image assets.',
    displayField: 'title',
    subField: 'category',
    statusField: 'visibility',
    fields: [
      { key: 'title', label: 'Photo Title', type: 'text', required: true },
      { key: 'photo_url', label: 'Photo URL', type: 'url', fullWidth: true, required: true },
      { key: 'caption', label: 'Caption', type: 'text', fullWidth: true },
      { key: 'photographer', label: 'Photographer', type: 'text' },
      { key: 'category', label: 'Category', type: 'select', options: ['Red Carpet', 'Ceremony', 'Networking', 'Awards', 'Behind the Scenes', 'Group Photo', 'Venue', 'Speakers', 'Exhibitors'] },
      { key: 'visibility', label: 'Visibility', type: 'select', options: ['Public', 'Private', 'VIP Only'] },
    ],
  },
  {
    id: 'videos',
    label: 'Manage Videos',
    icon: 'Video',
    type: 'video',
    description: 'Manage event videos, recordings, and livestream content.',
    displayField: 'title',
    subField: 'type',
    statusField: 'visibility',
    fields: [
      { key: 'title', label: 'Video Title', type: 'text', required: true },
      { key: 'video_url', label: 'Video URL', type: 'url', fullWidth: true, required: true, placeholder: 'YouTube, Vimeo, or direct link' },
      { key: 'type', label: 'Video Type', type: 'select', options: ['Highlights Reel', 'Full Recording', 'Winner Interviews', 'Promotional', 'Behind the Scenes', 'Speaker Sessions', 'Teaser'] },
      { key: 'duration', label: 'Duration', type: 'text', placeholder: 'e.g. 45 mins' },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'visibility', label: 'Visibility', type: 'select', options: ['Public', 'Private', 'Paid Access', 'Internal'] },
    ],
  },
  {
    id: 'checklist',
    label: 'Manage Checklist',
    icon: 'CheckSquare',
    type: 'checklist',
    description: 'Track all event planning tasks and their completion status.',
    displayField: 'task',
    subField: 'assignee',
    statusField: 'status',
    fields: [
      { key: 'task', label: 'Task', type: 'text', required: true, fullWidth: true, placeholder: 'e.g. Confirm venue layout with venue manager' },
      { key: 'category', label: 'Category', type: 'select', options: ['Venue', 'Catering', 'AV & Production', 'Marketing', 'Speakers', 'Sponsors', 'Logistics', 'Admin', 'Legal', 'Security', 'Other'] },
      { key: 'assignee', label: 'Assigned To', type: 'text' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Not Started', 'In Progress', 'Completed', 'Blocked', 'Cancelled'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'ticket_buyers',
    label: 'Manage Ticket Buyers',
    icon: 'Ticket',
    type: 'ticket_buyer',
    description: 'Track ticket sales, bookings, and payment statuses.',
    displayField: 'name',
    subField: 'ticket_type',
    statusField: 'payment_status',
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'ticket_type', label: 'Ticket Type', type: 'select', options: ['Early Bird', 'Standard', 'VIP', 'Premium VIP', 'Student', 'Group', 'Corporate Table', 'Complimentary'] },
      { key: 'quantity', label: 'Quantity', type: 'number', placeholder: '1' },
      { key: 'amount', label: 'Amount (£)', type: 'number' },
      { key: 'booking_ref', label: 'Booking Reference', type: 'text' },
      { key: 'payment_status', label: 'Payment Status', type: 'select', options: ['Pending', 'Paid', 'Partial', 'Refunded', 'Cancelled'] },
      { key: 'purchase_date', label: 'Purchase Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'judge',
    label: 'Manage Judge',
    icon: 'Scale',
    type: 'judge',
    description: 'Manage judges, their expertise, and category assignments.',
    displayField: 'name',
    subField: 'company',
    statusField: 'status',
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'job_title', label: 'Job Title', type: 'text' },
      { key: 'company', label: 'Company / Organisation', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'expertise', label: 'Area of Expertise', type: 'text', fullWidth: true },
      { key: 'categories', label: 'Categories Assigned', type: 'text', fullWidth: true, placeholder: 'Category names, comma-separated' },
      { key: 'bio', label: 'Biography', type: 'textarea', fullWidth: true },
      { key: 'photo_url', label: 'Photo URL', type: 'url', fullWidth: true },
      { key: 'linkedin_url', label: 'LinkedIn URL', type: 'url', fullWidth: true },
      { key: 'status', label: 'Status', type: 'select', options: ['Invited', 'Confirmed', 'Briefed', 'Scoring', 'Completed', 'Declined'] },
    ],
  },
  {
    id: 'hosts',
    label: 'Manage Hosts',
    icon: 'Mic2',
    type: 'host',
    description: 'Manage MCs, co-hosts, and stage presenters for the event.',
    displayField: 'name',
    subField: 'role',
    statusField: 'status',
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'role', label: 'Role', type: 'select', options: ['Master of Ceremonies (MC)', 'Co-Host', 'Stage Host', 'Award Presenter', 'Opening Ceremony Lead', 'Closing Ceremony Lead'] },
      { key: 'company', label: 'Company / Agency', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'fee', label: 'Fee (£)', type: 'number' },
      { key: 'bio', label: 'Biography', type: 'textarea', fullWidth: true },
      { key: 'requirements', label: 'Special Requirements', type: 'textarea', fullWidth: true },
      { key: 'status', label: 'Status', type: 'select', options: ['Enquired', 'Negotiating', 'Confirmed', 'Briefed', 'Completed', 'Declined'] },
    ],
  },
  {
    id: 'supporter',
    label: 'Manage Supporter',
    icon: 'Heart',
    type: 'supporter',
    description: 'Track individual and organisational supporters of the event.',
    displayField: 'name',
    subField: 'company',
    statusField: 'level',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'company', label: 'Company / Organisation', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'tel' },
      { key: 'type', label: 'Supporter Type', type: 'select', options: ['Individual', 'Corporate', 'Community Group', 'Academic', 'Charity', 'Government'] },
      { key: 'level', label: 'Support Level', type: 'select', options: ['Gold', 'Silver', 'Bronze', 'In-Kind', 'Volunteer'] },
      { key: 'contribution', label: 'Contribution / Value', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
  },
  {
    id: 'survey',
    label: 'Manage Survey',
    icon: 'ClipboardList',
    type: 'survey',
    description: 'Create and manage event surveys for feedback and data collection.',
    displayField: 'title',
    subField: 'target_audience',
    statusField: 'status',
    fields: [
      { key: 'title', label: 'Survey Title', type: 'text', required: true, placeholder: 'e.g. Post-Event Feedback Survey' },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'target_audience', label: 'Target Audience', type: 'select', options: ['All Attendees', 'Winners', 'Nominees', 'Sponsors', 'Exhibitors', 'Judges', 'Speakers', 'VIP Guests', 'Volunteers'] },
      { key: 'due_date', label: 'Response Deadline', type: 'date' },
      { key: 'survey_url', label: 'Survey Link / URL', type: 'url', fullWidth: true },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Active', 'Closed', 'Analysing'] },
      { key: 'responses', label: 'Total Responses', type: 'number' },
    ],
  },
  {
    id: 'survey_contacts',
    label: 'Survey Contacts',
    icon: 'UserCheck',
    type: 'survey_contact',
    description: 'Track who has been sent surveys and their response status.',
    displayField: 'name',
    subField: 'survey_title',
    statusField: 'status',
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'survey_title', label: 'Survey', type: 'text', required: true, placeholder: 'Survey name or title' },
      { key: 'sent_date', label: 'Date Sent', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Sent', 'Opened', 'Completed', 'Bounced', 'Opted Out'] },
    ],
  },
];
